name: nomo_router
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
